services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - env.docker.local
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - env.docker.local
    stdin_open: true
    tty: true
    depends_on:
      - db

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    env_file:
      - env.docker.local
    depends_on:
      - redis
      - rails

volumes:
  db_data:
  redis_data:
  bundle:
